"""Initial migration.

Revision ID: 9335473cab6e
Revises: 
Create Date: 2023-11-10 17:53:11.546954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9335473cab6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               nullable=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=45),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
